version: '2'
services:

  db:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:3307:3306 # change ip if required
    volumes:
      # for init: comment after the first docker-compose up
      - ./db-init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: words
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    restart: unless-stopped

  web:
    build: .
    ports:
      - 127.0.0.1:80:80 # change ip if required
    volumes:
      # sites directory: override the sources
      - ./src:/var/www/450words
    env_file: .env-local
    depends_on:
      - db
    links:
      - db:db 
