version: '2'
services:

  database_default:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:3307:3306 # change ip if required
    volumes:
      # for init: comment after the first docker-compose up
      - ./db-init:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
      - .:/app:rw
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_MANAGER: "fsm-mysql"
    healthcheck:
        test: "/usr/bin/mysql --user=root -h 127.0.0.1 --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

  web:
    build: .
    ports:
      - 127.0.0.1:80:80 # change ip if required
    volumes:
      # sites directory: override the sources
      - ./src:/app:rw
    env_file: .env-local
    links:
      - database_default
